// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJDScDBswQ4HddVtSZ42kZYU1Mv0xURo',
    appId: '1:554443647221:web:8be845812940bdd626fdbc',
    messagingSenderId: '554443647221',
    projectId: 'lost-and-found-6da1d',
    authDomain: 'lost-and-found-6da1d.firebaseapp.com',
    storageBucket: 'lost-and-found-6da1d.appspot.com',
    measurementId: 'G-SGYXL1D3MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOuQZ09XbMwdjJzbbKeBltq8Vop-9l6QA',
    appId: '1:554443647221:android:47ccecd03fd8350c26fdbc',
    messagingSenderId: '554443647221',
    projectId: 'lost-and-found-6da1d',
    storageBucket: 'lost-and-found-6da1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzXSFlkq3TDevodAqVeQ4J6JD6WL6YFMQ',
    appId: '1:554443647221:ios:f19a488de3d5cf7726fdbc',
    messagingSenderId: '554443647221',
    projectId: 'lost-and-found-6da1d',
    storageBucket: 'lost-and-found-6da1d.appspot.com',
    androidClientId: '554443647221-1tbl3ao3tp4lqh89dbl27sppsf2906h0.apps.googleusercontent.com',
    iosClientId: '554443647221-ge1dvn5gihflsvo8scrjaq5vochhpruu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzXSFlkq3TDevodAqVeQ4J6JD6WL6YFMQ',
    appId: '1:554443647221:ios:fc1454109e6ab4c326fdbc',
    messagingSenderId: '554443647221',
    projectId: 'lost-and-found-6da1d',
    storageBucket: 'lost-and-found-6da1d.appspot.com',
    androidClientId: '554443647221-1tbl3ao3tp4lqh89dbl27sppsf2906h0.apps.googleusercontent.com',
    iosClientId: '554443647221-lkdiomc05fc361i2mivp6f68hjtsgk3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.lf.RunnerTests',
  );
}
